---
- name: Crear infraestructura mínima para WireGuard
  hosts: localhost
  connection: local
  gather_facts: no

  vars:
    region: "us-east-1"
    vpc_cidr: "10.0.0.0/16"
    subnet_cidr: "10.0.1.0/24"
    key_name: "key_lab"   # Cambia por tu keypair ya creado en AWS
    instance_type: "m8g.2xlarge"
    ami_id: "ami-026fccd88446aa0bf" # Ubuntu 24.04 LTS (cambia si quieres Ubuntu 25.x cuando salga estable)

  tasks:
    - name: Crear VPC
      amazon.aws.ec2_vpc_net:
        name: "VPC-WireGuard"
        cidr_block: "{{ vpc_cidr }}"
        region: "{{ region }}"
        dns_hostnames: true
        dns_support: true
        state: present
      register: vpc

    - name: Crear Subnet pública
      amazon.aws.ec2_vpc_subnet:
        vpc_id: "{{ vpc.vpc.id }}"
        cidr: "{{ subnet_cidr }}"
        region: "{{ region }}"
        map_public: true
        state: present
        tags:
          Name: "Subnet-WireGuard"
      register: subnet

    - name: Crear Internet Gateway
      amazon.aws.ec2_vpc_igw:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        state: present
      register: igw

    - name: Crear Route Table y asociar
      amazon.aws.ec2_vpc_route_table:
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        subnets:
          - "{{ subnet.subnet.id }}"
        routes:
          - dest: 0.0.0.0/0
            gateway_id: "{{ igw.gateway_id }}"
        tags:
          Name: "RT-WireGuard"

    - name: Crear Security Group
      amazon.aws.ec2_security_group:
        name: "SG-WireGuard"
        description: "Permitir SSH y WireGuard"
        vpc_id: "{{ vpc.vpc.id }}"
        region: "{{ region }}"
        rules:
          - proto: tcp
            ports: [22]
            cidr_ip: 0.0.0.0/0
          - proto: udp
            ports: [51820]
            cidr_ip: 0.0.0.0/0
        rules_egress:
          - proto: -1
            cidr_ip: 0.0.0.0/0
      register: sg

    - name: Crear instancia EC2 Ubuntu
      amazon.aws.ec2_instance:
        name: "EC2-WireGuard"
        region: "{{ region }}"
        key_name: "{{ key_name }}"
        instance_type: "{{ instance_type }}"
        image_id: "{{ ami_id }}"
        vpc_subnet_id: "{{ subnet.subnet.id }}"
        security_group: "{{ sg.group_id }}"
        #assign_public_ip: true
        network:
          assign_public_ip: true
        wait: true
        state: running
        volumes:
          - device_name: /dev/sda1      # Root device
            ebs:
              volume_size: 50             # Tamaño en GB
              delete_on_termination: true
      register: ec2

    - name: Mostrar IP pública
      debug:
        msg: "Conéctate a tu EC2: ssh -i {{ key_name }}.pem ubuntu@{{ ec2.instances[0].public_ip_address }}"