apiVersion: v1
kind: ConfigMap
metadata:
  name: nats-config
data:
  nats.conf: |
    # NATS Server Configuration
    port: 4222
    http_port: 8222
    server_name: nats-cluster
    
    # Cluster configuration
    cluster {
      port: 6222
      routes = [
        "nats://nats-cluster:6222"
      ]
    }
    
    # JetStream configuration
    jetstream {
      store_dir: "/data"
      max_memory: 1GB
      max_file: 10GB
    }
    
    # Logging
    log_file: "/var/log/nats.log"
    logtime: true
    debug: false
    trace: false
    
    # Monitoring
    monitoring {
      http_port: 8222
    }
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nats-cluster
spec:
  serviceName: nats-cluster
  replicas: 1
  selector:
    matchLabels:
      app: nats-cluster
  template:
    metadata:
      labels:
        app: nats-cluster
    spec:
      containers:
      - name: nats
        image: nats:2.9-alpine
        ports:
        - containerPort: 4222
          name: client
        - containerPort: 6222
          name: cluster
        - containerPort: 8222
          name: monitor
        command:
        - "/nats-server"
        - "--config"
        - "/etc/nats/nats.conf"
        volumeMounts:
        - name: config
          mountPath: /etc/nats
        - name: data
          mountPath: /data
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /varz
            port: 8222
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /varz
            port: 8222
          initialDelaySeconds: 5
          periodSeconds: 5
      volumes:
      - name: config
        configMap:
          name: nats-config
      - name: data
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nats-cluster
spec:
  selector:
    app: nats-cluster
  ports:
  - name: client
    port: 4222
    targetPort: 4222
  - name: cluster
    port: 6222
    targetPort: 6222
  - name: monitor
    port: 8222
    targetPort: 8222
  type: ClusterIP
