apiVersion: keda.sh/v1alpha1
kind: ScaledObject
metadata:
  name: purchase-order-service-scaler
  namespace: default
spec:
  scaleTargetRef:
    name: purchase-order-service
  minReplicaCount: 1
  maxReplicaCount: 15
  triggers:
  - type: rabbitmq
    metadata:
      host: "amqp://mediplus:mediplus123@rabbitmq-cluster:5672/"
      queueName: "order.events"
      queueLength: "3"
  - type: prometheus
    metadata:
      serverAddress: "http://prometheus:9090"
      metricName: "order_requests_per_second"
      threshold: "15"
      query: "rate(http_requests_total{job=\"purchase-order-service\"}[1m])"
  - type: cpu
    metadata:
      type: Utilization
      value: "80"
  - type: memory
    metadata:
      type: Utilization
      value: "75"
  pollingInterval: 30
  cooldownPeriod: 300
  idleReplicaCount: 1
