apiVersion: apps/v1
kind: Deployment
metadata:
  name: purchase-order-service
  labels:
    app: purchase-order-service
    version: v1
spec:
  replicas: 2
  selector:
    matchLabels:
      app: purchase-order-service
      version: v1
  template:
    metadata:
      labels:
        app: purchase-order-service
        version: v1
      annotations:
        sidecar.istio.io/inject: "true"
    spec:
      containers:
      - name: purchase-order-service
        image: edwinhc93/medisupply-purchase-order-service:latest
        ports:
        - containerPort: 8081
          name: http
        env:
        - name: PORT
          value: "8081"
        - name: AWS_REGION
          value: "us-east-1"
        - name: AWS_ACCESS_KEY_ID
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: access-key-id
        - name: AWS_SECRET_ACCESS_KEY
          valueFrom:
            secretKeyRef:
              name: aws-credentials
              key: secret-access-key
        - name: DYNAMODB_ENDPOINT
          value: "http://dynamodb-local:8000"
        - name: RABBITMQ_URL
          value: "amqp://mediplus:mediplus123@rabbitmq:5672/"
        - name: SUPPLIER_SERVICE_URL
          value: "http://supplier-service:8080"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "256Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "1000m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 30
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 5
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 3
        startupProbe:
          httpGet:
            path: /health
            port: 8081
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 3
          failureThreshold: 30
---
apiVersion: v1
kind: Service
metadata:
  name: purchase-order-service
  labels:
    app: purchase-order-service
spec:
  selector:
    app: purchase-order-service
  ports:
  - port: 8081
    targetPort: 8081
    name: http
  type: ClusterIP
