apiVersion: apps/v1
kind: Deployment
metadata:
  name: supplier-service
  labels:
    app: supplier-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: supplier-service
  template:
    metadata:
      labels:
        app: supplier-service
    spec:
      containers:
      - name: supplier-service
        image: mediplus/supplier-service:latest
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: AWS_REGION
          value: "us-east-1"
        - name: RABBITMQ_URL
          value: "amqp://mediplus:mediplus123@rabbitmq-cluster:5672/"
        - name: ENVIRONMENT
          value: "production"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        livenessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
---
apiVersion: v1
kind: Service
metadata:
  name: supplier-service
spec:
  selector:
    app: supplier-service
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
